apiVersion: apps/v1
kind: Deployment
metadata: 
  name: devops-bank-deployment 
  labels: 
    app: devops-bank-deploy-file
    tier: frontend
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: devops-bank-deploy-file
  template:
    metadata: 
      name: devops-bank-deploy-file
      labels: 
        app: devops-bank-deploy-file
        tier: frontend
    spec:
      containers:
      - name: bank-app
        image: aaronhood/devopsbankapp:2.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
