apiVersion: apps/v1
kind: Deployment
metadata: 
    name: devops-bank-deploy-file
    labels: 
        app: devops-bank-deploy-file
        tier: frontend
spec:
  selector: 
    labels:
    app: devops-bank-deploy-file
  template:
    metadata: 
     name: devops-bank-deploy-file
     labels: 
        app: devops-bank-deploy-file
        tier: frontend
    spec:
      containers:
      - name: bank-app
      image: aaronhood/devopsbankapp:2.0
      ports:
      - containerPort: 80
      resources: 
        limits:
          cpu: "2"
          memory: "1Gi"
  replicas: 3
