apiVersion: v1
kind: Service
metadata: 
    name: devops-bank-pod-file
    labels: 
        app: devops-bank-pod-file
        tier: frontend
spec:
   selector: 
     app: devops-bank-deploy-file
   type: NodePort
   ports:
   - port: 80
     nodePort: 30210 
