apiVersion: v1
kind: Service
metadata: 
    name: devops-bank-pod-file
    labels: 
        app: devops-bank-pod-file
        tier: frontend
spec:
   type: NodePort
   ports:
   - targetPort: 3000
     port: 80
     nodePort: 30080
